# Generated by Django 3.2.7 on 2021-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeownership',
            name='permission',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('ADMIN', 'Admin'), ('WRITE', 'Write'), ('READ', 'Read')], default='READ', max_length=7, verbose_name='User permission to fridger'),
        ),
    ]
