# Generated by Django 3.2.7 on 2021-12-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0003_auto_20211229_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridge',
            options={},
        ),
    ]
