# Generated by Django 3.2.7 on 2022-01-10 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0004_alter_fridge_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
