# Generated by Django 3.2.7 on 2021-12-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fridges', '0001_initial'),
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity_type', models.CharField(choices=[('PIECE', 'Piece'), ('ML', 'Ml'), ('L', 'L'), ('G', 'G'), ('KG', 'Kg')], max_length=5)),
                ('is_available', models.BooleanField(default=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_product', to='fridges.fridge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingListProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('quantity_type', models.CharField(choices=[('PIECE', 'Piece'), ('ML', 'Ml'), ('L', 'L'), ('G', 'G'), ('KG', 'Kg')], max_length=5)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_product', to='shopping_lists.shoppinglist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingListProductHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATOR', 'Creator'), ('BUYER', 'Buyer'), ('TAKER', 'Taker')], default='CREATOR', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('qauntity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_product_history', to='products.shoppinglistproduct')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_product_history', to='shopping_lists.shoppinglist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FridgeProductHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used'), ('WASTED', 'Wasted'), ('UNTRACKED', 'Untracked')], default='UNUSED', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_product_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_product_history', to='products.fridgeproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
