# Generated by Django 3.2.7 on 2021-12-12 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_fridgeproducthistory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='qauntity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='status',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('BUYER', 'Buyer'), ('TAKER', 'Taker')], default='CREATOR', max_length=7),
        ),
        migrations.DeleteModel(
            name='ShoppingListProductHistory',
        ),
    ]
