# Generated by Django 3.2.7 on 2021-12-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211212_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
