# Generated by Django 3.2.7 on 2021-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shoppinglistproduct_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shoppinglistproduct',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='shoppinglistproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistproduct',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('TAKER', 'Taker'), ('TAKER_MARKED', 'Taker marked'), ('BUYER', 'Buyer')], default='FREE', max_length=12),
        ),
    ]
