# Generated by Django 3.2.7 on 2021-12-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0005_auto_20211218_1412'),
        ('products', '0007_auto_20211218_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='shopping_list_fragment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_product', to='shopping_lists.shoppinglistfragment'),
        ),
    ]
