# Generated by Django 3.2.7 on 2021-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shoppinglistproduct_shopping_list_fragment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistproduct',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
