# Generated by Django 3.2.7 on 2021-12-29 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20211226_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistproduct',
            name='created_by',
        ),
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
