# Generated by Django 3.2.7 on 2021-12-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211229_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistproduct',
            options={},
        ),
    ]
