# Generated by Django 3.2.7 on 2021-12-30 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_shoppinglistproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
