# Generated by Django 3.2.7 on 2021-12-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211128_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_token',
            field=models.CharField(blank=True, max_length=60, verbose_name='Mobile push token'),
        ),
    ]
