# Generated by Django 3.2.7 on 2021-12-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0002_alter_fridgeownership_permission'),
        ('shopping_lists', '0003_auto_20211211_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='fridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list', to='fridges.fridge'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
