# Generated by Django 3.2.7 on 2021-12-18 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_lists', '0004_auto_20211212_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistfragment',
            name='shopping_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_fragment', to='shopping_lists.shoppinglist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglistfragment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_fragment', to=settings.AUTH_USER_MODEL),
        ),
    ]
