# Generated by Django 3.2.7 on 2021-12-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0002_alter_fridgeownership_permission'),
        ('shopping_lists', '0005_auto_20211218_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='fridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list', to='fridges.fridge'),
        ),
    ]
