# Generated by Django 3.2.7 on 2021-12-29 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0007_delete_shoppinglistfragment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
