# Generated by Django 3.2.7 on 2022-01-12 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0009_alter_shoppinglist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistownership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
